version: '3.3'

volumes:
  static_value:
  media_value:
  postgres_value:


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: anthonyhol/foodgram-backend:latest
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/recipes/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: anthonyhol/foodgram-frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/recipes/
    depends_on:
      - backend
      - frontend
    restart: always
